### ISSUE TITLE
Accessing job/project properties

### ISSUE THREAD

**Issue by Dids** [Strider-CD/strider-slack#11]
What's the correct format when trying to access job/project properties and send those to Slack, so I could at least know what project it's referring to?

**Comment by keyvanfatehi** [comment]
hi

check out the default strings in https://github.com/Strider-CD/strider-slack/blob/master/schema.js

**Comment by Dids** [comment]
OK, so essentially the same formatting as with ejs. Thanks!

**Comment by keyvanfatehi** [comment]
yep, it uses ejs under the hood -- explore the mongodb database "job" object to learn more -- also check out https://github.com/Strider-CD/strider-metadata it exposes the same object but has a nice interactive interface and a nice readme with a screenshot.
